apply plugin: 'com.android.application'

repositories {
    google()
    mavenCentral()
}

ext {
    buildToolsVersion = "33.0.0"
    versionCode = 46
    versionName = "3.9.6"
}

android {
    compileSdkVersion 33

    defaultConfig {
        applicationId 'org.dkf.jmule'
        versionCode project.ext.versionCode
        versionName project.ext.versionName
        minSdkVersion 21
        targetSdkVersion 33
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java {
                srcDir 'src/main'
            }
        }
        androidTest {
            java.srcDirs = ['src/androidTest']
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }

    flavorDimensions "app"

    productFlavors {
        basic {
            versionCode 0001 + project.ext.versionCode
            resValue "string", "application_label", "Mule"
        }
    }

    lint {
        abortOnError false
    }
}

dependencies {
    implementation project(':core')
    implementation 'androidx.appcompat:appcompat:1.5.1'
    implementation 'androidx.preference:preference:1.2.0'
    implementation 'androidx.documentfile:documentfile:1.0.1'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.5.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.5.1'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'com.google.re2j:re2j:1.6'
    implementation 'com.google.code.gson:gson:2.8.8'
    implementation 'com.squareup.okhttp:okhttp:2.7.5'
    implementation 'com.google.android.material:material:1.7.0'
}