apply plugin: 'java'
apply plugin: 'application'

group = 'org.dkf.jed2k'
version = '2.0'

description = "jed2k console application"

repositories {
    mavenCentral()
}

application {
    mainClass = 'org.dkf.jed2k.Conn'
}

jar {
    manifest {
        attributes 'Main-Class': 'org.dkf.jed2k.Conn'
    }
}

task fatJar(type: Jar) {
    manifest {
        attributes 'Main-Class': 'org.dkf.jed2k.Conn'
    }
    archiveClassifier = 'all'
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    } {
        exclude "META-INF/*.SF"
        exclude "META-INF/*.DSA"
        exclude "META-INF/*.RSA"
    }
    with jar
}

run {
    standardInput = System.in
}

dependencies {
    implementation project(':core')
    implementation 'com.google.code.gson:gson:2.7'
}
